//! Configuration parser for the pipeline help YAML output.
//!
//! This module fetches the pipeline's `--help` output (generated by `discover.sh --print-help`)
//! as a flat YAML mapping of environment variable names to their help text,
//! and converts it into a `ConfigSchema` for the UI to display and edit.
//!
//! Other responsibilities: loading/saving per-project `config.sh` files.

use crate::runtimes::{Runtime, RuntimeFactory};
use colmap_openmvs_api::{
    ConfigSchema, EnvVarConfig, EnvVarWithHelp, LoadedProjectConfig, SavedProjectConfig,
};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;
use tokio::io::AsyncReadExt;

/// Root schema for the YAML help output (new flat env-var format)
#[derive(Debug, Clone, Serialize, Deserialize)]
struct HelpSchema {
    environment_variables: BTreeMap<String, EnvVarHelp>,
}

/// Help text for a single environment variable
#[derive(Debug, Clone, Serialize, Deserialize)]
struct EnvVarHelp {
    help: String,
}

/// Parse configuration from a prepared container image by running help commands.
/// Uses the runtime specified in the default_image_tag from settings.
pub async fn get_image_config(image_tag: String) -> dioxus::Result<ConfigSchema> {
    let settings = crate::settings::get_settings()
        .await
        .map_err(|e| anyhow::anyhow!("Failed to retrieve settings: {:?}", e))?
        .clone();
    let (runtime, _) = settings.parse_default_image();

    tracing::debug!(
        image_tag = %image_tag,
        default_image_tag = ?settings.default_image_tag,
        parsed_runtime = ?runtime,
        "get_image_config: Settings loaded and parsed"
    );

    match runtime {
        Some("docker") => {
            tracing::debug!("get_image_config: Selected Docker runtime");
            get_image_config_with_docker(image_tag).await
        }
        Some(other) => {
            tracing::debug!(runtime = %other, "get_image_config: Selected runtime from prefix");
            get_image_config_with_proot(image_tag).await
        }
        None => {
            tracing::debug!(
                "get_image_config: No runtime prefix in default_image_tag, using PRoot"
            );
            get_image_config_with_proot(image_tag).await
        }
    }
}

/// Parse configuration using PRoot runtime.
async fn get_image_config_with_proot(image_tag: String) -> dioxus::Result<ConfigSchema> {
    let rt = RuntimeFactory::proot().await;
    get_image_config_impl(&rt, image_tag).await
}

/// Parse configuration using Docker runtime.
async fn get_image_config_with_docker(image_tag: String) -> dioxus::Result<ConfigSchema> {
    let rt = RuntimeFactory::docker();
    get_image_config_impl(&rt, image_tag).await
}

/// Shared implementation for getting image configuration from any runtime.
async fn get_image_config_impl(
    rt: &dyn Runtime,
    image_tag: String,
) -> dioxus::Result<ConfigSchema> {
    // First, try to get the image build date from the list of prepared images
    let build_date = match rt.list_images().await {
        Ok(images) => images
            .iter()
            .find(|img| img.tag_str() == image_tag)
            .and_then(|img| img.build_date.clone()),
        Err(_) => None,
    };

    // Get help output (the discover.sh --print-help YAML)
    let full_help = get_tool_help(rt, &image_tag, "ignored").await?;
    let full_help_schema: HelpSchema = serde_saphyr::from_str::<HelpSchema>(&full_help)
        .map_err(|e| anyhow::anyhow!("Failed to parse help YAML: {}", e))?;

    // Build environment_variables list directly from the flat mapping
    let environment_variables: Vec<EnvVarWithHelp> = full_help_schema
        .environment_variables
        .into_iter()
        .map(|(name, var)| EnvVarWithHelp {
            name,
            help: Some(var.help),
        })
        .collect();

    Ok(ConfigSchema {
        image_tag,
        build_date,
        environment_variables,
    })
}

/// Run a tool's help command inside the container and capture output.
async fn get_tool_help(
    rt: &dyn crate::runtimes::Runtime,
    image_tag: &str,
    ignored: &str,
) -> anyhow::Result<String> {
    let args = vec![ignored.to_string(), "--help".to_string()];

    let mut handle = rt.run(image_tag, &args, &[], &[]).await?;

    let stdout = handle
        .take_stdout()
        .ok_or_else(|| anyhow::anyhow!("Failed to capture stdout from {} --help", ignored))?;

    let stderr = handle
        .take_stderr()
        .ok_or_else(|| anyhow::anyhow!("Failed to capture stderr from {} --help", ignored))?;

    // Read from stdout
    let mut output = Vec::new();
    let mut stdout_reader = tokio::io::BufReader::new(stdout);
    stdout_reader.read_to_end(&mut output).await?;

    // Also read stderr in case help is written there
    let mut stderr_output = Vec::new();
    let mut stderr_reader = tokio::io::BufReader::new(stderr);
    stderr_reader.read_to_end(&mut stderr_output).await?;

    // Wait for the process to finish and check exit code
    let status = handle.wait().await?;

    if !status.success() {
        let code = status.code().unwrap_or(-1);
        let stdout_str = String::from_utf8_lossy(&output);
        let stderr_str = String::from_utf8_lossy(&stderr_output);
        return Err(anyhow::anyhow!(
            "{} --help failed with exit code {}\nstdout:\n{}\nstderr:\n{}",
            ignored,
            code,
            stdout_str,
            stderr_str
        ));
    }

    let stdout_str = String::from_utf8_lossy(&output).to_string();
    let stderr_str = String::from_utf8_lossy(&stderr_output).to_string();

    // Combine outputs, preferring stdout
    let combined = if !stdout_str.is_empty() {
        stdout_str
    } else {
        stderr_str
    };

    Ok(combined)
}

/// Load and parse project configuration from config.sh in a project directory.
pub(crate) async fn load_project_config_by_path(
    project_path: String,
) -> dioxus::Result<LoadedProjectConfig> {
    let project_path = Path::new(&project_path);

    if !project_path.exists() {
        return Err(
            anyhow::anyhow!("Project path does not exist: {}", project_path.display()).into(),
        );
    }

    let config_path = project_path.join("config.sh");

    if !config_path.exists() {
        return Err(
            anyhow::anyhow!("config.sh not found in project: {}", config_path.display()).into(),
        );
    }

    let content = tokio::fs::read_to_string(&config_path).await?;

    // Parse the config.sh file
    let mut image_tag = String::new();
    let mut environment_variables = Vec::new();
    let mut custom_script = String::new();
    let mut in_env_vars = false;
    let mut in_custom_script = false;

    for line in content.lines() {
        // Extract image tag from comment
        if line.trim_start().starts_with("# Generated from image:") {
            if let Some(tag) = line.split("# Generated from image:").nth(1) {
                image_tag = tag.trim().to_string();
            }
        }

        // Check for custom script markers
        if line.trim() == "# ===== BEGIN CUSTOM SCRIPT =====" {
            in_custom_script = true;
            continue;
        }
        if line.trim() == "# ===== END CUSTOM SCRIPT =====" {
            in_custom_script = false;
            continue;
        }

        // Capture custom script if we're in the marked section
        if in_custom_script {
            custom_script.push_str(line);
            custom_script.push('\n');
            continue;
        }

        // Parse environment variables
        if line.trim_start().starts_with("export ") {
            in_env_vars = true;
            if let Some(env_line) = parse_env_var_line(line) {
                environment_variables.push(env_line);
            }
        } else if in_env_vars && !line.trim().is_empty() && !line.trim_start().starts_with('#') {
            // End of environment variables section
            in_env_vars = false;
        }
    }

    // Clean up trailing newline from custom script
    if custom_script.ends_with('\n') {
        custom_script.pop();
    }

    Ok(LoadedProjectConfig {
        image_tag,
        environment_variables,
        custom_script,
    })
}

pub async fn load_project_config(project_name: String) -> dioxus::Result<LoadedProjectConfig> {
    let project_path = crate::project::resolve_project_path(&project_name)
        .await
        .map_err(|e| anyhow::anyhow!("{}", e))?;
    load_project_config_by_path(project_path.to_string_lossy().into_owned()).await
}

/// Parse a single environment variable export line
fn parse_env_var_line(line: &str) -> Option<EnvVarConfig> {
    let line = line.trim();
    if !line.starts_with("export ") {
        return None;
    }

    let rest = &line[7..]; // Skip "export "

    // Find the equals sign
    if let Some(eq_pos) = rest.find('=') {
        let name = rest[..eq_pos].trim().to_string();
        let value_part = &rest[eq_pos + 1..];

        // Parse the value, handling both single and double quotes
        let value = if value_part.starts_with('\'') && value_part.len() > 1 {
            // Single quoted - find closing quote
            if let Some(close_pos) = value_part[1..].find('\'') {
                value_part[1..close_pos + 1].to_string()
            } else {
                return None;
            }
        } else if value_part.starts_with('"') && value_part.len() > 1 {
            // Double quoted - find closing quote and unescape
            if let Some(close_pos) = value_part[1..].find('"') {
                let raw_value = &value_part[1..close_pos + 1];
                // Unescape double-quoted string
                raw_value
                    .replace("\\\\", "\\")
                    .replace("\\\"", "\"")
                    .replace("\\$", "$")
                    .replace("\\`", "`")
            } else {
                return None;
            }
        } else {
            // Unquoted value (shouldn't normally happen but handle it)
            value_part.trim().to_string()
        };

        return Some(EnvVarConfig { name, value });
    }

    None
}

/// Save environment variable configuration to config.sh in a project directory.
pub(crate) async fn save_project_config_by_path(
    project_path: String,
    config: SavedProjectConfig,
) -> dioxus::Result<()> {
    let project_path = Path::new(&project_path);

    if !project_path.exists() {
        return Err(
            anyhow::anyhow!("Project path does not exist: {}", project_path.display()).into(),
        );
    }

    let mut script_content = String::new();
    script_content.push_str("#!/bin/bash\n");
    script_content.push_str("# Configuration for COLMAP/OpenMVS pipeline\n");
    script_content.push_str(&format!("# Generated from image: {}\n", config.image_tag));
    script_content.push_str(&format!(
        "# Generated at: {}\n",
        chrono::Local::now().to_rfc3339()
    ));
    script_content.push_str("#\n");
    script_content.push_str("# Usage: source ./config.sh\n");
    script_content.push_str("# Then run your COLMAP/OpenMVS commands\n");
    script_content.push('\n');

    if config.environment_variables.is_empty() {
        script_content.push_str("# No environment variables configured\n");
    } else {
        script_content.push_str("# Environment variables\n");
        for env_var in &config.environment_variables {
            let escaped_value = if env_var.value.contains('\'') {
                format!(
                    "\"{}\"",
                    env_var
                        .value
                        .replace('\\', "\\\\")
                        .replace('"', "\\\"")
                        .replace('$', "\\$")
                        .replace('`', "\\`")
                )
            } else {
                format!("'{}'", env_var.value)
            };
            script_content.push_str(&format!("export {}={}\n", env_var.name, escaped_value));
        }
    }

    // Add custom script section if provided
    if let Some(custom_script) = &config.custom_script {
        if !custom_script.is_empty() {
            script_content.push_str("\n# ===== BEGIN CUSTOM SCRIPT =====\n");
            script_content.push_str(custom_script);
            if !custom_script.ends_with('\n') {
                script_content.push('\n');
            }
            script_content.push_str("# ===== END CUSTOM SCRIPT =====\n");
        }
    }

    script_content.push_str("\necho \"Configuration loaded from $0\"\n");

    let config_path = project_path.join("config.sh");
    tokio::fs::write(&config_path, &script_content).await?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o755);
        std::fs::set_permissions(&config_path, perms)?;
    }

    Ok(())
}

pub async fn save_project_config(
    project_name: String,
    config: SavedProjectConfig,
) -> dioxus::Result<()> {
    let project_path = crate::project::resolve_project_path(&project_name)
        .await
        .map_err(|e| anyhow::anyhow!("{}", e))?;
    save_project_config_by_path(project_path.to_string_lossy().into_owned(), config).await
}
