# https://medium.com/@aarne.laur/retry-failed-github-actions-8661e7601c66
on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true
jobs:
  rerun:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:
      - env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run watch ${{ inputs.run_id }} || true
          gh run rerun ${{ inputs.run_id }} --failed
